import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Brain Tumor MRI Classifier",
    page_icon="🧠",
    layout="centered"
)

# -----------------------------
# Load Model
# -----------------------------
MODEL_PATH = "efficientnetb0_final.keras"

@st.cache_resource
def load_model():
    return tf.keras.models.load_model(MODEL_PATH)

model = load_model()

# -----------------------------
# Prediction Function
# -----------------------------
def predict_mri(image):
    image = image.convert("RGB")
    image = image.resize((224, 224))

    image_array = np.array(image)
    image_array = image_array.astype(np.float32)

    image_array = np.expand_dims(image_array, axis=0)

    probability = model.predict(image_array, verbose=0)[0][0]

    if probability >= 0.5:
        prediction = "Tumour"
        confidence = probability * 100
    else:
        prediction = "Non-Tumour"
        confidence = (1 - probability) * 100

    return prediction, confidence


# -----------------------------
# UI
# -----------------------------
st.title("🧠 Brain Tumor MRI Classifier")

st.write(
    "Upload a brain MRI image and the trained EfficientNetB0 "
    "model will classify it as Tumour or Non-Tumour."
)

uploaded_file = st.file_uploader(
    "Upload MRI Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(
        image,
        caption="Uploaded MRI",
        use_container_width=True
    )

    if st.button("🔍 Predict"):

        prediction, confidence = predict_mri(image)

        st.subheader("Prediction")

        if prediction == "Tumour":
            st.error(f"🧠 {prediction}")
        else:
            st.success(f"✅ {prediction}")

        st.metric(
            "Model Confidence",
            f"{confidence:.2f}%"
        )

        st.info(
            "Note: This prediction is generated by a machine learning "
            "model and should not be considered a medical diagnosis."
        )
